export const countriesByContinent = {
  Europe: {
    Albania: "al",
    Austria: "at",
    Belgium: "be",
    Bulgaria: "bg",
    Croatia: "hr",
    Cyprus: "cy",
    Czechia: "cz",
    Denmark: "dk",
    Estonia: "ee",
    Finland: "fi",
    France: "fr",
    Germany: "de",
    Greece: "gr",
    Hungary: "hu",
    Iceland: "is",
    Ireland: "ie",
    Italy: "it",
    Latvia: "lv",
    Lithuania: "lt",
    Luxembourg: "lu",
    Malta: "mt",
    Netherlands: "nl",
    Norway: "no",
    Poland: "pl",
    Portugal: "pt",
    Romania: "ro",
    Slovakia: "sk",
    Slovenia: "si",
    Spain: "es",
    Sweden: "se",
    Switzerland: "ch",
    "United Kingdom": "gb",
    Ukraine: "ua",
  },

  Americas: {
    Canada: "ca",
    Mexico: "mx",
    "United State of America": "us",
    Argentina: "ar",
    Brazil: "br",
    Chile: "cl",
    Colombia: "co",
    Peru: "pe",
    Venezuela: "ve",
    Bolivia: "bo",
    Ecuador: "ec",
    Paraguay: "py",
    Uruguay: "uy",
    Guyana: "gy",
    Suriname: "sr",
    "Costa Rica": "cr",
    Cuba: "cu",
    Jamaica: "jm",
    Panama: "pa",
    Haiti: "ht",
    "Dominican Republic": "do",
  },

  Asia: {
    Afghanistan: "af",
    Armenia: "am",
    Azerbaijan: "az",
    Bahrain: "bh",
    Bangladesh: "bd",
    Bhutan: "bt",
    Brunei: "bn",
    Cambodia: "kh",
    China: "cn",
    Georgia: "ge",
    India: "in",
    Indonesia: "id",
    Iran: "ir",
    Iraq: "iq",
    Israel: "il",
    Japan: "jp",
    Jordan: "jo",
    Kazakhstan: "kz",
    Kuwait: "kw",
    Kyrgyzstan: "kg",
    Laos: "la",
    Lebanon: "lb",
    Malaysia: "my",
    Maldives: "mv",
    Mongolia: "mn",
    Myanmar: "mm",
    Nepal: "np",
    "North Korea": "kp",
    Oman: "om",
    Pakistan: "pk",
    Philippines: "ph",
    Qatar: "qa",
    "Saudi Arabia": "sa",
    Singapur: "sg",
    "South Korea": "kr",
    "Sri Lanka": "lk",
    Syria: "sy",
    Taiwan: "tw",
    Tajikistan: "tj",
    Thailand: "th",
    Turkey: "tr",
    Turkmenistan: "tm",
    UAE: "ae",
    Uzbekistan: "uz",
    Vietnam: "vn",
    Yemen: "ye",
  },
};
export const getCountryCode = (countryName) => {
  if (!countryName) return null;

  for (const continent in countriesByContinent) {
    const code = countriesByContinent[continent][countryName];
    if (code) return code;
  }

  return null;
};